name: 🐛 Bug Report
description: Report a reproducible bug

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT — AI DISCLOSURE REQUIRED**

        You must disclose whether AI tools were used in any part of the affected code,
        configuration, tests, or reproduction steps.  
        Missing or misleading disclosures will result in the issue being closed.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have written a clear and specific issue title
          required: true
        - label: I have searched existing issues and discussions
          required: true
        - label: I understand that low-effort or incomplete reports may be closed
          required: true

  - type: textarea
    id: ai-disclosure
    attributes:
      label: AI Usage Disclosure
      description: |
        Single-line answer required.

        Answer **exactly one** of the following:
        - `No AI used`
        - `AI used: <tool> / <area> / <purpose>`

        Example:
        `AI used: ChatGPT / test generation / boilerplate only`
      placeholder: No AI used
    validations:
      required: true

  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: List all relevant version numbers.
      placeholder: |
        Project version:
        Runtime / platform:
        OS:
    validations:
      required: true

  - type: input
    id: mre
    attributes:
      label: Minimal Reproducible Example
      placeholder: https://github.com/username/repro-example
      description: |
        ⚠️ Issues without a minimal reproducible example are treated as **low priority**.

        Provide a repository or link that allows maintainers to reproduce the issue
        with minimal setup.

        See: https://stackoverflow.com/help/minimal-reproducible-example
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clearly describe what is wrong.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Provide exact steps, commands, or code.
        Include stack traces in a GitHub code block.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
