name: 🐛 Bug Report
description: Report a bug to help us improve

body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have written a clear issue title
          required: true
        - label: I have searched existing issues to avoid duplicates
          required: true

  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: List all relevant version numbers.
    validations:
      required: true
      
  - type: input
    id: mre
    attributes:
      label: A minimal reproducible example
      placeholder: https://github.com/my-username/bug-example-that-im-reporting
      description: |
        ⚠️ Issues opened without a minimal reproducible example are going to be treated with low priority.

        A repository URL containing a reproducible example that will help out contributors to reproduce your
        bug in an attempt to find where the problem is.

        https://stackoverflow.com/help/minimal-reproducible-example.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the issue clearly.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Provide steps, sample code, or a link to a project that reproduces the issue.
        Include stack traces in a [code block](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
